openapi: "3.0.2"
info:
  title: Auth Service
  version: "1.0"
servers:
  - url: http://localhost:5000/api/v1
components:
  schemas:
    User:
      type: object
      required:
        - "email"
        - "password"
      properties:
        email:
          type: string
          format: email
          example: illiadev93@gmail.com
        password:
          type: string
          format: password
          example: wE564879
paths:
  /users:
    get:
      responses:
        "200":
          description: OK
  /registration:
    post:
      description: Register a new user
      operationId: registration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        "200":
          description: OK
  /login:
    post:
      description: Login a user
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        "200":
          description: OK
  /activate/{activationLink}:
    get:
      description: Activate user
      operationId: activate
      parameters:
        - in: path
          name: activationLink
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
